### PR TITLE
Fixes #24 print out equivalent curl command when `verbose` 

### LINKED ISSUE #24: `--curl` flag to print out curl cmd
https://github.com/moul/http2curl

### PR DESCRIPTION
**Pull request by cuichenli**
Feel this is helpful when debugging - especially at the moment the `solution list` command is broken but the api can actually work via postman. 

Note: this is not a must have so feel free to reject.

### CODE REVIEW

**Comment by pnickolov** [comment]
@cuichenli , I will give it a try; one concern is that it may be logging the auth header(s)/credentials

**Comment by cuichenli** [comment]
> @cuichenli , I will give it a try; one concern is that it may be logging the auth header(s)/credentials

the intention was to have the command outputted so people can just copy and execute it right away. but yes, it may leak the credentials if user use it to post it somewhere for debug. guess i will change it to only log it out when the `--curl` option is specified.

**Comment by cuichenli** [comment]
@pnickolov The latest commit has the body issue fixed.

But now I am more concerned on the errors that might happen during generating the curl command - originally I was thinking to only do the conversion when the flag is enabled, but actually now, it will do the conversion all the time, only it would not get logged when `verbose` is not set. I am wondering if it would be better if we can pass those kind of configurations to the API call?  Thanks

**Comment by pnickolov** [comment]
Superseded by PR #74

**Pull request closed without merging**
